### ISSUE TITLE
Empty shop in sessions table

### ISSUE THREAD

**Issue by mahamudml** [kinngh/shopify-node-mongodb-next-app#10]
I see sometimes the shop is empty in sessions table
<img width="939" alt="Screenshot 2022-02-12 at 9 09 06 PM" src="https://user-images.githubusercontent.com/80940388/153717832-b98b3d27-92af-4bf4-a58f-ecb5fc03356d.png">

**Comment by mahamudml** [comment]
I had installed app for a week, and I found this in sessions table.

**Comment by kinngh** [comment]
Let me test this out and get back to you within a week. Though can you please decrypt one of the sessions where the shop is undefined and see if the response has returned a shop, since we're dumping it as-is?

**Comment by mahamudml** [comment]
I truncated the table. I have installed a new app, let me check if I get new undefined shops.

**Comment by mahamudml** [comment]
I was able to find one in local. After decrypt, the shop is undefined.

`{
  id: 'fbfb9396-68f1-48f4-b076-5d9845a08949',
  shop: 'undefined',
  state: '084913921564713',
  isOnline: true
}`

**Comment by kinngh** [comment]
If the return value is undefined I don't think there's anything that can be done to fix it? I'm sure there's an obvious answer to this but it doesn't affect the way the app functions so it's good to go, I believe. I've been building on top of this template for over a year now and haven't run into any issues _yet_.

**Comment by kinngh** [comment]
I've been running an app on Heroku with random GQL calls and activities and nothing seems to be broken just yet. Closing this issue. Incase someone reports something, I'll reopen and deal with it^
