### ISSUE TITLE
Shopify rejected: App must verify the authenticity of the request from Shopify.

### ISSUE THREAD

**Issue by TrevPennington** [kinngh/shopify-node-mongodb-next-app#11]
Do you know if this template passes Shopify app review? 
I set up my server.js like the one in this template to use authenticated requests and all but Shopify rejects my app: 

App must verify the authenticity of the request from Shopify.
Your app does not request installation on the shop immediately after clicking "add app". Apps must ask a shop for access when being installed on a shop for the first time, as well as when they are being reinstalled after having been removed. During install or reinstall we expected OAuth to be initiated at https://cambridgetestshop.myshopify.com/admin/oauth/request_grant but was redirected to https://cambridgetestshop.myshopify.com/admin/apps/xxxxxxxxxxx

Have you run into this before? 
Thanks!

**Comment by kinngh** [comment]
Thank you for raising this! Let me take a look into this and get back to you as soon as I've run tests. I'm working on an Express.js x React.js branch so focused on that, but this should be a quick fix

**Comment by kinngh** [comment]
Commit [2a770ce](https://github.com/kinngh/shopify-node-mongodb-next-app/commit/2a770ce3442fce2ab85fb3b8f73d1e5da1bb4c96) resolves this issue. Checking the urls seems to confirm the redirection is working as intended. Can you please confirm?

**Comment by TrevPennington** [comment]
That was quick! Yes that is going to the correct URL now.
Thank you!
