### ISSUE TITLE
Whats the correct value for whitelisting the redirect_uri 

### ISSUE THREAD

**Issue by avifatal** [kinngh/shopify-node-mongodb-next-app#2]
Hi
`Oauth error invalid_request: The redirect_uri is not whitelisted`

I have whitelisted the followings:
```
https://tttttttt.loca.lt/
https://tttttttt.loca.lt/auth/
https://tttttttt.loca.lt/auth/inline/
https://tttttttt.loca.lt/auth/callback/
```
Non of them works.
Can you please help with this config?
Thanks

**Comment by kinngh** [comment]
Add `https://localtunnel.local.lt` to your `SHOPIFY_APP_URL` variable in `.env` file. You can follow the `.env.example` file to make your `.env` file
