### ISSUE TITLE
update links in shopify store app setting (partner dashboard)

### ISSUE THREAD

**Issue by ismailalabou** [kinngh/shopify-node-mongodb-next-app#3]
hello @kinngh keep up the good work 🚀,

i just have one question, which is related to app setup (step 3);
in which you said: "add the URL at your app settings in your Partner Dashboard";
how i'm gonna be able to update my app setting, if the app isn't installed in my dev store in the first place ??

i tried this:
![image](https://user-images.githubusercontent.com/28371448/132162599-078f40d1-a45d-4911-9181-34d0fca25dbc.png)

**Comment by kinngh** [comment]
You first need to create a Custom or Public app from your Shopify Partner Dashboard. In the app url, you'll be using the URL generated by local tunnel which looks like `your-url.local.lt` and in the "Allowed redirection URL" section you'll be using `your-url.loca.lt/auth/callback`. 

Also, the repo doesn't work with the Shopify CLI just yet. I'll be adding support for CLI and/or extensions later.

**Comment by ismailalabou** [comment]
one more thing, local tunnel doesn't change, right ??
(i won't need to update it each time i want to start the app.)

**Comment by kinngh** [comment]
Every time you run `npm run tunnel` it generates a new URL. If you want to avoid that, you can change the `tunnel` script to include a subdomain. `lt --port 8081 --subdomain <your-sub-domain>` and that will generate the same subdomain every time, if it's available.

If you run into "URI not whitelisted" or similar issue, check your `.env` file and App Setup and make sure it's the same URL in both spaces.

**Comment by kinngh** [comment]
I've made a new commit with extended docs that should help you in setting up everything. [4237ac3](https://github.com/kinngh/shopify-node-mongodb-next-app/commit/4237ac3c01971c8c54f99a2d3e28af17f16481ba)

**Comment by ismailalabou** [comment]
thanks man, i really appreciate it.
