### ISSUE TITLE
mongodb atlas

### ISSUE THREAD

**Issue by ismailalabou** [kinngh/shopify-node-mongodb-next-app#4]
hello @kinngh, i have followed the setup guide you have provided.

it seems there is a connection issue, when i tried to link my app (.env) with a mongodb atlas database (cloud).

terminal throws this error:
![image](https://user-images.githubusercontent.com/28371448/132974228-780669ac-e027-4009-9848-b96cf7c03218.png)

i think u could easily provoke this issue by trying to link a cloud mongodb to your app, & see the error for yourself.

good luck!

**Comment by kinngh** [comment]
`connect ECONNREFSED 127.0.0.1:27017` You are still connecting to your local instance of MongoDB because there was a spelling error in `server.js` which is fixed in [18d8a82](https://github.com/kinngh/shopify-node-mongodb-next-app/commit/18d8a829ddddf2d4b8eecf72e80ed62bc6cbddb1).

**Comment by ismailalabou** [comment]
okay good, i'm gonna try this out 👍

**Comment by ismailalabou** [comment]
> `connect ECONNREFSED 127.0.0.1:27017`
> 
> You are still connecting to your local instance of MongoDB because there was a spelling error in `server.js` which is fixed in [18d8a82](https://github.com/kinngh/shopify-node-mongodb-next-app/commit/18d8a829ddddf2d4b8eecf72e80ed62bc6cbddb1).

this is weird cause i don't have a local instance of mongodb in my machine

**Comment by ismailalabou** [comment]
u were right, now it's working properly 👌;
one last question if u don't mind, how can i view the app in the browser ??

**Comment by kinngh** [comment]
> this is weird cause i don't have a local instance of mongodb in my machine; plus that message saying connected to MongoDB which means that mongoose is connecting the my cloud mongodb i have setup; P.S: i haven't tested yet, i'm just analyzing the behavior ...

`connected to MongoDB` is a logical bug that needs to be dealt with. Because your `.env` file contains `MONGO_URL` and `server.js` was calling `mongoURL`, it caused the server to look for a value that doesn't exist in the `.env` file.

---

> one last question if u don't mind, how can i view the app in the browser ??

I suggest you read the app developer documentation at [Shopify.dev](https://shopify.dev/apps/getting-started) to understand how embedded Shopify apps work. This channel is only for issues related to the repo^

**Comment by ismailalabou** [comment]
okay fair enough will do;
however do you have any idea that my database was populated with 6 different session tokens ??

**Comment by ismailalabou** [comment]
i asked because when running this command: `npm run dev` i tried to access the app by visiting the URL tunnel generated, but it didn't work out.

**Comment by kinngh** [comment]
Again, please first complete the basic documentation on how to create an app from [Shopify.dev](https://shopify.dev/apps/getting-started) before you start using a third party boilerplate template^
