### ISSUE TITLE
mandatory webhooks are not registered, yet.

### ISSUE THREAD

**Issue by ismailalabou** [kinngh/shopify-node-mongodb-next-app#5]
in order to correctly configure Shopify mandatory webhooks, i have to: 

> Add the following URLs in the GDPR section of my App Setup:
> 
> Data Request Endpoint: /app/gdpr/customers_data_request
> Data Erase Endpoint: /app/gdpr/customers_redact
> Shop Data Erase Endpoint: /app/gdpr/shop_redact

my question here, what URL should we specify, is it the one we got from running: `npm run tunnel`
or
my Shopify store domain name URL.

the screenshot below, shows that my store isn't subscribed to any webhooks, yet.
(0 webhooks registred)
![image](https://user-images.githubusercontent.com/28371448/133002952-8868cc72-d650-4b2e-95c0-304e3858979a.png)

**Comment by kinngh** [comment]
The URL `localtunnel-url`/app/gdpr/`route` should be registered in App Name > App Setup > GDPR Mandatory Webhooks from your Partner Dashboard. This isn't really necessary when learning / building out your app and is required when you're building production grade applications.

To understand how the GDPR endpoints work, please visit [the documentation](https://shopify.dev/apps/webhooks/mandatory).

Also, just a heads up this isn't the tutorial section and only issues related to the repo should be opened.

**Comment by ismailalabou** [comment]
thanks for the clarification, i really appreciate it!
