### ISSUE TITLE
Getting 403 on /graphql

### ISSUE THREAD

**Issue by mahamudml** [kinngh/shopify-node-mongodb-next-app#8]
The application was working fine for 2-3 days on heroku, but after restarting the app. It is throwing 403 error for /graphql endpoint

**Comment by kinngh** [comment]
In your env, can you try removing quotes from `SHOPIFY_API_VERSION`? Change it from `"2021-10"` to `2021-10` This is a fix that worked for me and I want to see if that's an issue from Heroku's side and then implement changes to the codebase

**Comment by mahamudml** [comment]
I had written without quotes. Don't know why, but sometime after reinstallation the app works fine.

**Comment by kinngh** [comment]
Is it possible to get a log of this?
